version: "3.7"

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: phonebook
      MYSQL_USER: admin
      MYSQL_PASSWORD: ersin_13
    networks:
      - clarusnet
  myapp:
    image: ersinsari/phone
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet
networks:
  clarusnet: